apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4.0.11-alpine
        command: [sh, -c, source /redis-config/init.sh]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: config
          mountPath: /redis-config 
        - name: data
          mountPath: /redis-data
      - name: sentinel
        image: redis:4.0.11-alpine
        command: [sh, -c, source /redis-config-src/sentinel.sh]
        volumeMounts:
          - mountPath: /redis-config-src
            name: config
          - mountPath: /redis-config
            name: data
      volumes:
      - configMap:
          defaultMode: 420
          name: redis-config
        name: config 
      - emptydirvolumesrc:
        name: data
        volumeMounts: 
        - mountPath: /redis-config 
          name: config 
        - mountPath: /redis-data 
          name: data
        - command: [sh, -c, source /redis-config/sentinel.sh]
          image: redis:3.2.7-alpine
          name: sentinel
          volumeMounts:
          - mountPath: /redis-config 
            name: config
