#!/bin/bash

cd ${HOME}/Documents/journal/daily/.

# Usage: cannt change directory by just calling command since shell runs in a
# subshell to run command. To run in current shell, you can either call:
# source cdaily
# . cdaily
