#!/bin/bash

echo "Hey Isabelle"
echo "Just going to download a few repositories and place them in Documents/git-littleBitta/."
echo " "
echo "To access this repo, just type cd Documents/git-littleBitta/."
echo " "

brew --version

if [[ $? -ne 0 ]]; then
    curl -fsSL "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
fi

brew install git

cd ~/Documents/.
mkdir git-littleBitta
cd git-littleBitta

git init
# git remote remove origin
# git remote add origin https://<auth_token>@github.com/<username>/<repo>.git
echo "Cloning the main AWS common repo..."
git clone https://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@github.com/louislef299/AWS_Environments.git

echo "Cloning the resources repo..."
git clone https://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@github.com/louislef299/terraform-aws-resources.git

echo "Cloning the EC2 repo..."
git clone https://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@github.com/louislef299/terraform-aws-ec2.git

echo "Cloning the VPC repo..."
git clone https://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@github.com/louislef299/terraform-aws-vpc.git

echo "All resources added and provided!"
echo "If you would like to see where the code is located, go to Finder and select Documents. There, you should find the littleBitta directory."
echo "I just made this script out of excitement for the project. You don't have to do anything for now."
echo "Have a nice night Isabelle. <3 u!"