#!/bin/bash

AWSDIR=${HOME}/Documents/self-work/aws 

function  generic_add {
    git pull
    terraform fmt

    echo "$(pwd)"

    git status
    git add .
    git commit -m "quick add"
    git push

    if [[ $1 == "main" ]]; then
        echo
        git branch
        git checkout main
        git merge devel
        git push
        echo
    fi
}

cd ${AWSDIR}/AWS_Environments/chat-ssh
generic_add

cd ${AWSDIR}/terraform-aws-ec2
generic_add

cd ${AWSDIR}/terraform-aws-resources
generic_add

cd ${AWSDIR}/terraform-aws-vpc
generic_add