#!/bin/bash

## This script is used to upload data to the Medtronic AWS account
## In order to function properly, you must include a .csv file to
## the function call.

## ex: > ./plexus-upload example.csv

export AWS_PROFILE="plexus"

if [ $# -eq 0 ] ; then
    echo "usage: ./plexus-upload <CSV file for monitor info>"
    exit 1

fi

aws s3 cp $1 s3://plexus-drop-bucket

if [ $? -eq 0 ]; then
    echo "Success! if your file was formatted correctly, nothing more needs to be done."
else
    echo "FAILURE: Please contact a Medtronic admin"
fi

export AWS_PROFILE="lz-terraform-ops"
